### ISSUE TITLE
Private Groups API

### ISSUE THREAD

**Issue by berkus** [FreeFeed/freefeed-server#11]
1. Support switching group to/from private, is_private flag
2. Make group user admin/remove admin status
3. For admins - kick user from group
4. Join requests for private groups (similar to subscriptions to private user)

The following methods have to be implemented
- [x] `/v1/groups/:groupName/sendRequest` — Send request to join the private Group
- [x] `/v1/groups/:groupName/acceptRequest/:userName` — Accept request. Only this group's administrator can do this. Should fail for user which doesn't have current request
- [x] `/v1/groups/:groupName/rejectRequest/:userName` — Decline request.  Only this group's administrator can do this. Should fail for user which doesn't have current request
- [ ] `/v1/groups/:groupName/unsubscribeFromGroup/:userName` — Kick user out of group. Only this group's administrator can do this.

The following methods have to be verified to work properly with private groups:
- [ ] `/v1/groups/:groupName/subscribers/:userName/admin`
- [ ] `/v1/groups/:groupName/subscribers/:adminName/unadmin`

Change existing methods:
- [x] `/v1/users/whoami` should get additional `pendingGroupRequests` property, which is a boolean

New V2 API method should be implemented:
- [x] `/v2/groupRequests` which returns PLAIN json object, not ember-friendly serialization (see below)

``` json
[
  {
    "username": "group1",
    "screenName": "The best group in the UNIVERSE",
    "requests": [{"username": "username1", "screenName": "John Doe"}, …]
  },
  …
]
```

**Comment by clbn** [comment]
So we'll have two switches: 
1. `isPrivate` — Reading entries is only allowed for members.
2. `isRestricted` — Posting entries is restricted to admins.

Non-members cannot post entries to the group, regardless of these switches. But comments can be posted by anyone who can see the posts.  

There were three group types in Old Frf:
1. Private group — Only the people you invite can view and post to the feed.
2. Standard feed — You (and other admins) can post messages, anyone can comment.
3. Public group — Anyone can post messages to and comment on the feed.

So we can represent these types with our switches:

```
--------------------------------------------------------------------
| Type                                  | isPrivate | isRestricted |
--------------------------------------------------------------------
| Private restricted group (NEW!)       | true      | true         |
| Private group                         | true      | false        |
| Restricted group (ex-"Standard feed") | false     | true         |
| Public group                          | false     | false        |
--------------------------------------------------------------------
```

**Comment by ujenjt** [comment]
I think that we need in `/v2/groupRequests` response `profilePictureLargeUrl` and `profilePictureMediumUrl` for each user.
