### ISSUE TITLE
Mentions sometimes do not trigger notification (possibly when the mention is added later?)

### ISSUE THREAD

**Issue by taivolints** [FreeFeed/freefeed-server#297]
There is a comment where my @username is mentioned (and I can see that comment), but this mention did NOT trigger a notification for me and it is NOT listed under my https://freefeed.net/filter/notifications. I was suggested that maybe this can happen when the comment initially did not mention me but was later edited and the mention was added later. (I have not tested if this is the way it happens).

**Comment by davidmz** [comment]
@taivolints, could you check if you are banned by author of the comment?

**Comment by taivolints** [comment]
@davidmz, checked, I am NOT banned by the author of the comment. The comment mentioned the usernames specifically with the goal to create notifications for them so that they would notice the post: https://freefeed.net/dsumin/213c1566-4f7a-4625-a6bd-8f524436bb2c

**Comment by davidmz** [comment]
Ok, thank you!
