### ISSUE TITLE
Invalid email

### ISSUE THREAD

**Issue by k0fi** [FreeFeed/freefeed-server#308]
Hi,
I'm trying to register at freefeed.net by my gmail but get `Invalid email` error, which is really frustrating, as I'm so keen to test this app. Is this a bug, or I'm missing something?
Appreciate your help.

**Comment by dsumin** [comment]
What email are you using to register?

**Comment by k0fi** [comment]
I was using `gmail`. Interestingly, when I tried a 10minutemail disposable email, I could register, though did not receive any welcome email.

**Comment by dsumin** [comment]
It appears that you have already registered. You could request password reset at https://freefeed.net/restore

**Comment by k0fi** [comment]
I don't think so. I tried to retrive the password but got `Invalid email address or user not found`.

**Comment by dsumin** [comment]
Could you please let me know your exact email address (or send it to dmitry.sumin@gmail.com). I'll try to troubleshoot the issue.
