### ISSUE TITLE
Network error after registration

### ISSUE THREAD

**Issue by k0fi** [FreeFeed/freefeed-server#313]
I have a fresh install of FreeFeed on my local Ubuntu machine. 
When I register a user, I see that the user is created on the database, but on the frontend I get `Network Error` message. 

 and I get this error in the console:

`Failed to load http://localhost:3000/v1/session: The 'Access-Control-Allow-Origin' header has a value 'http://localhost:3333' that is not equal to the supplied origin. Origin 'http://127.0.0.1:3333' is therefore not allowed access. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

I get the same error when I try to login as the user.

How can I fix it?

**Comment by indeyets** [comment]
everything's in the error

You should open website as http://localhost:3333/ not it's IP address.

this is the way CORS is set up
