### ISSUE TITLE
How to deploy on server?

### ISSUE THREAD

**Issue by k0fi** [FreeFeed/freefeed-server#316]
Hello,
After development on my local machine, I'm going to deploy freefeed-server on my remote Debian server.  
I could not find any hints on the docs about deployment, so appreciate your clarifications.

**Comment by indeyets** [comment]
well… that's what you use https://github.com/FreeFeed/freefeed-ansible for.
install ansible on debian-server, attach recipes execution to github hook (or use travis, or any other mean which works for you) and you're set.

**Comment by k0fi** [comment]
Oh please, I'm sick and tired of ansible. I'm going to install it directly on Debian, as I did on my local Ubuntu machine.  

What I did on the server was to create a new set of username/password on postgresql and used them at `knexfile.js` for both `development` and `production`. But then `./node_modules/.bin/knex migrate:latest` results in:

`Knex:warning - migration file "20180415062651_pg_trgm_idx.js" failed
Knex:warning - migration failed with error: CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public - permission denied to create extension "pgcrypto"
error: permission denied to create extension "pgcrypto"
    at Connection.parseE (/srv/freefeed-server/node_modules/pg/lib/connection.js:545:11)
    at Connection.parseMessage (/srv/freefeed-server/node_modules/pg/lib/connection.js:370:19)
    at Socket.<anonymous> (/srv/freefeed-server/node_modules/pg/lib/connection.js:113:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
`

Any hints on how to fix this?

**Comment by indeyets** [comment]
oh… then it should be directly installable just like locally. but be aware that `20180415062651_pg_trgm_idx` migration is actually going away reall-really soon (15 minutes). it was a failed experiment

regarding your error: it is not freefeed-specific. extensions are installable strictly by postgres super-users and noone else. our usual process is to enable them manually before running migrations

**Comment by k0fi** [comment]
Ok, for the record, here is what I've done and worked:

I created a database useing postgres user:

```
   Name    |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges   
-----------+----------+----------+-------------+-------------+-----------------------
mydb     | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
```

And defined `mydb` with a password in knexfile.js

```
  production: {
    client: 'postgresql',
    connection: {
      database: 'mydb',
      user:     'postgres',
      password: 'supersecret'
    },

```

Then defined  the password for `postgres`. 

`ALTER USER postgres PASSWORD 'supersecret';`

And then could do the database migration. Thanks for the tip!
