### ISSUE TITLE
404 after deployment

### ISSUE THREAD

**Issue by k0fi** [FreeFeed/freefeed-server#317]
Hello,
I have difficulty deploying the app on the server:
I copied the whole `freefeed-server` from local machine to the server and changed `config.js` .

and the node server is started without error:
```
root@server:/srv/freefeed-server# npm start

> freefeed-server@1.45.0 start /srv/freefeed-server
> babel-node index.js
```
Now when I visite mysite.com, the site and its css files are rendered but for all image assets  I get `404` error despite the fact that I gave 777 permission to `assets`.

 for `socket.io` i get this error on browser:

`POST http://mysite.com/socket.io/?EIO=3&transport=polling&t=MCflZYQ 405 (Not Allowed)
` 

Here is the `config.js` on the server:

```
const config = {
  api:{
    host: 'http://mysite.com/api',
    sentinel: null // keep always last
  },
  auth: {
    cookieDomain: 'mysite.com',
    tokenPrefix: 'mysite',
    userStorageKey: 'somethingspecial',
    sentinel: null // keep always last
  },
  captcha: {
    siteKey: '',
    sentinel: null // keep always last
  },
  search: {
    searchEngine: null,
    sentinel: null // keep always last
  },
  siteDomains: [ // for transform links in the posts, comments, etc.
    'mysite.com'
  ],
  sentry: {
    publicDSN: null,
    sentinel: null // keep always last
  },
  frontendPreferences: {
    clientId: 'net.mysite',
    defaultValues: {
      displayNames: {
        displayOption: FrontendPrefsOptions.DISPLAYNAMES_DISPLAYNAME,
        useYou: true
      },
      realtimeActive: false,
      comments: {
        omitRepeatedBubbles: true,
        highlightComments: true,
        hiddenTypes: []
      },
      allowLinksPreview: false,
      readMoreStyle: 'modern',
      homefeed: {
        hideUsers: []
      }
    }
  }
};

export default config;
```

and my nginx config:

```
server {
  listen 80 default_server;
  server_name mysite.com;
  root /www/app;

  location / {
    try_files $uri /index.html;
  }
  location /assets {
   root /www/app/assets;
  }
  location ~ ^.+\..+$ {
    try_files $uri =404;
  }
  location /api {
    proxy_pass http://127.0.0.1:3000;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection  ^`^xupgrade ^`^y;
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
  }
}

```
Appreciate your hints to fix this.

**Comment by indeyets** [comment]
try `location ~ ^/assets/ {` instead of what you have

**Comment by k0fi** [comment]
Well, it did not solve the issue. 

Hoping to resolve the problem, I changed the config to server the api from a  subdomain 'api.mysite.com` and rebuild the client

That is:

```
  api:{
    host: 'http://api.mysite.com',
....
```

Here is my new nginx config file:



```

server {
  listen mysite.com:80 default_server;
  server_name mysite.com;
  root /www/app;

  location / {
   root /www/app;
   try_files $uri /index.html;
  }
  location ~ ^/assets/ {
   root /www/app/assets;
  }
  location ~ ^.+\..+$ {
    try_files $uri =404;
  }
}

#Now api is served from subdomain
server {
  listen api.mysite.com:80;
  server_name api.mysite.com;
  location / {
   proxy_pass http://127.0.0.1:3000;
   proxy_http_version 1.1;
   proxy_set_header X-Forwarded-Proto https;
   proxy_set_header Upgrade $http_upgrade;
   proxy_set_header Connection 'upgrade';
   proxy_set_header Host $host;
   proxy_cache_bypass $http_upgrade;
  }
}
```


But still get `404` for asstes and 
The socet.io has:

```
socket connect undefined
subscribing to global:users

```

But when I try to register a user, I get:

`Failed to load http://api.mysite.com/v1/users: The 'Access-Control-Allow-Origin' header has a value 'http://localhost:3333' that is not equal to the supplied origin. Origin 'http://mysite.com' is therefore not allowed access. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

Any ideas to fix these? Can you share sample working config for production?

**Comment by indeyets** [comment]
Sorry, I'm not good at server configuration. Probably someone with more experience will join here.

regarding last error: you have to change `origin` setting in `config/environments/production.js` (or whatever environment you use)

**Comment by k0fi** [comment]
There is no `production.js` in `config/` folder. How can I create and use it?

**Comment by indeyets** [comment]
default env is development. you specify other one by altering environment. for example `NODE_ENV=production yarn start` will start server with production environment.

you can copy current development.js to production.js and fine-tune it to your needs

**Comment by k0fi** [comment]
Alright, thanks to your tip I could resolve the CORS problem by modifying the environment varibales. 

But now I get `500` error when I try to register a user:

`POST http://api.mysite.com/v1/users 500 (Internal Server Error)`

Any tip to resolve this?

**Comment by k0fi** [comment]
Alright, thanks to your tip I could resolve the CORS problem by modifying the environment varibales.

Also or the record, the assets problem is solved by modifying nginx config to:

```
 location ~ ^/assets/ {
   root /www/app;
  }

```
