### ISSUE TITLE
Wrong path for images on the server

### ISSUE THREAD

**Issue by k0fi** [FreeFeed/freefeed-server#319]
Hi,
When users upload images on  the server they are still displayed from `http://localhost:3000/` path  like this:

`<img width="75" height="75" src="http://localhost:3000/profilepics/a3763500-e29e-4496-bb14-bc9f4880dd34_75.jpg" style="">`

So the images are not displayed and I get `404` instead. 

How can I fix this? 

Thanks

**Comment by indeyets** [comment]
path to images in specified in `environment/production.js` too.

see https://github.com/FreeFeed/freefeed-server/blob/stable/config/environments/development.js#L67 for example
