### ISSUE TITLE
all-groups 404 error

### ISSUE THREAD

**Issue by k0fi** [FreeFeed/freefeed-server#321]
Hello,
When I try to access `http://localhost:3333/all-groups/` I get `404` error, while I see no errors in the terminal debuggin mode. 

socket.io response:

```
  socket.io:socket sending ack [{"success":true,"rooms":{"global":["users"]}}] +0ms
  socket.io:client writing packet {"id":3,"type":3,"data":[{"success":true,"rooms":{"global":["users"]}}],"nsp":"/"} +0ms
  socket.io-parser encoding packet {"id":3,"type":3,"data":[{"success":true,"rooms":{"global":["users"]}}],"nsp":"/"} +2ms
  socket.io-parser encoded {"id":3,"type":3,"data":[{"success":true,"rooms":{"global":["users"]}}],"nsp":"/"} as 33[{"success":true,"rooms":{"global":["users"]}}] +0ms

```

**Comment by dsumin** [comment]
I suggest that you use Google Chrome Developer Tools (or similar) to inspect API calls/results.

socket.io is for handling realtime events only.

**Comment by k0fi** [comment]
Here is what I get in the dev console after I try to get`http://localhost:3333/all-groups/` :

index.js?http://0.0.0.0:3333:153 ./src/redux/reducers.js

```
/home/me/freefeed-react-client/src/redux/reducers.js
  574:5  warning  Unexpected 'todo' comment  no-warning-comments

✖ 1 problem (0 errors, 1 warning)

 @ ./src/redux/configure-store.js 8:0-39
 @ ./src/index.jsx
 @ multi (webpack)-dev-server/client?http://0.0.0.0:3333 webpack/hot/dev-server babel-polyfill ./src
```

On `FreeFeed.net` the link  is rendered by an external url. So I suppose there is somthing missing in the code?

**Comment by dsumin** [comment]
Yes, for FreeFeed.net all-groups is handled by an external service.

**Comment by k0fi** [comment]
So does this mean that the present code on github is lacking this 'show all groups' feature?

**Comment by dsumin** [comment]
Yes, "show all groups" is an external project done by @davidmz

**Comment by k0fi** [comment]
If the code is available, can you please refer me to the code to render `all-groups`? I could not find it @davidmz

**Comment by davidmz** [comment]
@k0fi There is no repository for the all-groups. You can view source of https://davidmz.me/frfrfr/all-groups/ and copy it to your site - it is pure client-side page consists of elementary HTML and few JS/CSS.

Also, could you open the topic https://freefeed.net/support for further questions about your installation? Most of them are not related to the FF code and just litter the issues list here.
