### ISSUE TITLE
Best Of Digest email color and other issues

### ISSUE THREAD

**Issue by dsumin** [FreeFeed/freefeed-server#324]
![image](https://user-images.githubusercontent.com/2417937/39928936-5fa02c5a-553f-11e8-83be-3176c77c1cf7.png)

1. Изменить текст на: Hello username, the entries below were ...

2. Запись не подзамочная, но замочек показывается. (проверить работу для public, protected и private accounts).

3. Поменять цвет сердечка на тот же, что и на сайте.

4. Не показываются облачка перед комментами.

**Comment by davidmz** [comment]
У свёрнутых комментов написано, например, “3 more comments with 2 likes”, но в видимых комментах лайки комментариев, кажется, не отображаются. Если они и не должны отображаться, то, наверное, и в свёрнутых про них писать не надо.
