### ISSUE TITLE
Group-search is slower than dedicated group-endpoint

### ISSUE THREAD

**Issue by indeyets** [FreeFeed/freefeed-server#372]
It is considerably slower to do a search for all posts from group than to fetch them via dedicated endpoint.

Compare:
* https://freefeed.net/v2/timelines/development?offset=0 = 375ms
* https://freefeed.net/v2/search?qs=group%3Adevelopment&offset=0 = 34708ms

That's 2 orders of magnitude difference. They should be (almost?) the same

**Comment by davidmz** [comment]
Fixed in current search engine
