### ISSUE TITLE
Change sendRequest endpoint response

### ISSUE THREAD

**Issue by ujenjt** [FreeFeed/freefeed-server#48]
In the `whoami` response there is field `requests` in which is listed all group requests. This is cool, because I can display 'Subscription requested' label on the group page instead of 'Request subscription' button, when request to the group had already sent.

I suggest:

For now `/v1/groups/:groupName/sendRequest` returns `{}` in case of success. It would be convenient to have more verbose response contained sent request description.

Like this:

```
{
  "id":"63d0410f-098a-461d-bbb9-83a912e020fa",
  "username":"testgroup",
  "screenName":"testgroup",
  "profilePictureLargeUrl":"",
  "profilePictureMediumUrl":""
}
```

**Comment by ujenjt** [comment]
@indeyets @berkus @clbn @golozubov ^

**Comment by clbn** [comment]
What is the problem you are solving with this?

**Comment by ujenjt** [comment]
@clbn I don't want to do `whoami` request after `/v1/groups/:groupName/sendRequest`

**Comment by clbn** [comment]
I'm sorry, it's not clear for me. Why do you need to do `whoami`?
