### ISSUE TITLE
trivial risk reduction with docker base image bump up to node:18.16.1-bookworm

### ISSUE THREAD

**Issue by silpol** [FreeFeed/freefeed-server#633]
[Snyk](https://snyk.io/) scanner for Docker files suggests to bump up version of base image to reduce various risks

![image](https://github.com/FreeFeed/freefeed-server/assets/43109/9e00644d-dd00-40ac-9900-34e8191b556a)

pull request can be applied to try impact on current codebase

**Comment by indeyets** [comment]
@silpol this is a major upgrade. NodeJS 18.x is still a supported branch. are you sure those issues are not fixable?

Can you add more details about problems which snyk reports?

**Comment by indeyets** [comment]
oh, here's the link: https://snyk.io/test/docker/node%3A18.16.1-buster

it looks like the problems are not really node related, but distro related.

can we change distro instead?

**Comment by indeyets** [comment]
will this work maybe? https://snyk.io/test/docker/node%3A18.16.1-bookworm

**Comment by silpol** [comment]
@indeyets ok, it makes sense, I have updated pull request
